[package]
name = "halo_2"
version = "0.1.0"
edition = "2024"

[dependencies]
ff = "0.13.1"
rand = "0.9.0"
rand_chacha = "0.9.0"
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v0.3.0" }
